/*
 * Jakefile
 * TestJake
 *
 * Created by Thomas Balthazar on November 24, 2009.
 * Copyright 2009, Suit My Mind SPRL All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    // configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";
	configuration = "Release";

app ("TestJake", function(task)
{
    /* task.setBuildIntermediatesPath(FILE.join("Build", "TestJake.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration)); */

    task.setBuildIntermediatesPath(FILE.join("Build", "TestJake.build", configuration));
    task.setBuildPath(FILE.join("..", "public", configuration));

    task.setProductName("dev diaries");
    task.setIdentifier("com.suitmymind.devdiaries");
    task.setVersion("1.0");
    task.setAuthor("Suit My Mind SPRL");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("TestJake");
    task.setSources(new FileList("**/*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["TestJake"]);
